preprocessing:
  drop_columns:
    - PatientID
    - DoctorInCharge
    - BMI
    - AlcoholConsumption
    - PhysicalActivity
    - DietQuality
    - DiastolicBP
    - CholesterolTotal
    - CholesterolTriglycerides
    - Gender
    - EducationLevel
    - Diabetes
    - Disorientation
    - Forgetfulness
  map_change_columns:
    Ethnicity:
      0: 'Caucasian'
      1: 'African American'
      2: 'Asian'
      3: 'Other'
  one_hot_columns: ['Ethnicity']
  scale_columns:
    - ADL
    - Age
    - CholesterolHDL
    - CholesterolLDL
    - FunctionalAssessment
    - MMSE
    - SleepQuality
    - SystolicBP
  passthrough_columns: 
    - BehavioralProblems
    - CardiovascularDisease
    - Confusion
    - Depression
    - DifficultyCompletingTasks
    - FamilyHistoryAlzheimers
    - HeadInjury
    - Hypertension
    - MemoryComplaints
    - PersonalityChanges
    - Smoking

  raw_data_path: ../data/raw/alzheimers_disease_data.csv
  raw_train_path: ../data/raw/train.csv
  raw_test_path: ../data/raw/test.csv
  unique_values_path: ../data/processed/unique_values.json
  test_size: 0.2
  target_column: 'Diagnosis'
  random_state: 42

train:
  n_folds: 3
  random_state: 42
  target_column: 'Diagnosis'
  model_path: ../pipeline_steps/model_svc.joblib
  col_transform_path: ../pipeline_steps/column_transformer.joblib
  metrics_path: ../report/metrics.json
  params_path: ../report/best_params.json

permutation_importances:
  n_repeats: 15
  random_state: 42
  permutation_importances_path: ../report/perm_imp.csv

endpoints:
  train: 'http://fastapi:8000/train'
  prediction_input: 'http://fastapi:8000/predict_input'
  prediction_from_file: 'http://fastapi:8000/predict'
  # train: 'http://localhost:8000/train'
  # prediction_input: 'http://localhost:8000/predict_input'
  # prediction_from_file: 'http://localhost:8000/predict'